### ISSUE TITLE
[수정] LookService base path 변경

### ISSUE THREAD

**Issue by greatSumini** [DEV-MUGLES/pickk-super-admin#27]
- 기존 : /looks/
- 변경 후 : /super/looks/

캐시 문제로 인해 슈퍼어드민용 엔드포인트를 추가했습니다!
아래와 같이 변경 후 잘 작동하는지 테스트 해주세요 😄 

작은 변경점이니 master에서 변경/테스트 후 바로 push하셔도 됩니다

**Comment by syoung125** [comment]
변경해서 테스트 해보았는데 전이랑 같아요 😂😭
